labels:
  app: swagger-ui
replicas: 1
image:
  name: swaggerapi/swagger-ui
  tag: v4.15.5
ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/base-url-scheme: "http"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.org/proxy-connect-timeout: "600s"
    nginx.org/proxy-read-timeout: "600s"
  hosts:
  - swagger
  tls:
  - secretName: swagger-https-certificate
    hosts:
    - swagger
certificate:
  crt: some-crt
  key: some-key
use_le: true
