{{ if eq .Values.use_le false }}
apiVersion: v1
kind: Secret
metadata:
  name: swagger-https-certificate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  tls.crt: {{ .Values.certificate.crt | b64enc }}
  tls.key: {{ .Values.certificate.key | b64enc }}
type: kubernetes.io/tls
{{end}}