apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ui-nginx-ingress
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: swagger-ui
              port:
                number: 8080
  {{- end }}
