apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-swagger-ui
  selector:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}