gitlab:
  webservice:
    resources:
      limits:
       cpu: 2     
       memory: 4G
      requests:
        cpu: 300m
        memory: 2.5G
  sidekiq:
    resources:
      limits:
        cpu: 2
        memory: 2G
      requests:
        cpu: 900m
        memory: 1.5G
        