apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
        }
        reload
        loop
        bind 169.254.20.10 10.96.128.2
        forward . __PILLAR__CLUSTER__DNS__ {
                prefer_udp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }
    in-addr.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10 10.96.128.2
        forward . __PILLAR__CLUSTER__DNS__ {
                prefer_udp
        }
        prometheus :9253
        }
    ip6.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10 10.96.128.2
        forward . __PILLAR__CLUSTER__DNS__ {
                prefer_udp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10 10.96.128.2
        forward . __PILLAR__UPSTREAM__SERVERS__
        prometheus :9253
        }
