---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 1iu-ingress-binding-ok
  namespace: ok
roleRef:
  kind: ClusterRole
  apiGroup: ""
  name: 1iu-ingress-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: ok
  apiGroup: ""